### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

### ISSUE THREAD

**Issue by 2dlabharryharry** [SystemErrorWang/White-box-Cartoonization#30]
hello, i`m trying to run cartoonize.py or pretrain.py and everytime i have same error:

python cartoonize.py
2020-07-30 13:32:57.785610: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "cartoonize.py", line 5, in <module>
    import network
  File "C:\Users\Admin\Desktop\dfl\White-box-Cartoonization-master\White-box-Cartoonization-master\test_code\network.py", line 3, in <module>
    import tensorflow.contrib.slim as slim
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 40, in <module>
    from tensorflow.contrib import coder
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\contrib\coder\__init__.py", line 22, in <module>
    from tensorflow.contrib.coder.python.ops.coder_ops import *
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\coder_ops.py", line 22, in <module>
    from tensorflow.contrib.coder.python.ops import gen_coder_ops
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\gen_coder_ops.py", line 99, in <module>
    _ops.RegisterShape("PmfToQuantizedCdf")(None)
**_AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'_**

more info:
cuda is 10.1
scikit-image==0.14.5
tensorflow-gpu==1.12.0

**Comment by SystemErrorWang** [comment]
@2dlabharryharry This is a tensorflow problem, I would like to know if you can successfully run other tensorflow code? Especially, if you can run any code with tf.slim ops?

**Comment by 2dlabharryharry** [comment]
> @2dlabharryharry This is a tensorflow problem, I would like to know if you can successfully run other tensorflow code? Especially, if you can run any code with tf.slim ops?

this is my installed tf: 

tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-estimator==2.3.0
tensorflow-gpu==1.12.0

**Comment by 2dlabharryharry** [comment]
> @2dlabharryharry This is a tensorflow problem, I would like to know if you can successfully run other tensorflow code? Especially, if you can run any code with tf.slim ops?

how can i check it?

**Comment by 2dlabharryharry** [comment]
solved by downgrading tf to ==1.15
