### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by Humanemy** [SystemErrorWang/White-box-Cartoonization#6]
WARNING:tensorflow:From White-box-Cartoonization/test_code/cartoonize.py:38: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Traceback (most recent call last):
  File "White-box-Cartoonization/test_code/cartoonize.py", line 65, in <module>
    cartoonize(load_folder, save_folder, model_path)
  File "White-box-Cartoonization/test_code/cartoonize.py", line 39, in cartoonize
    saver.restore(sess, tf.train.latest_checkpoint(model_path))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

I'm using tf-gpu==1.15

**Comment by amrwc** [comment]
Try changing the current working directory to `test_code`.

```bash
cd test_code
python ./cartoonize.py
```

**Comment by amrwc** [comment]
https://github.com/SystemErrorWang/White-box-Cartoonization/pull/8
